{% set name = "logaddexp" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/horta/logaddexp/archive/{{ version }}.tar.gz
  sha256: b8a9e10ce1b45315b2663bb38641c3625d197e7c6e2a43983918a3ee95dd5642

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make  # [unix]
test:
  commands:
    - test -e $PREFIX/include/logaddexp/logaddexp.h            # [unix]

about:
  home: https://github.com/horta/logaddexp
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: C library that implements the logarithm of the sum of exponentiations
  dev_url: https://github.com/horta/logaddexp

extra:
  recipe-maintainers:
    - horta
