{% set name = "logaddexp" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/horta/logaddexp/archive/{{ version }}.tar.gz
  sha256: 514657c423eff857e6b1c9e119d81577183e3c73942b0116b01be46f08573c93

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make  # [unix]
test:
  commands:
    - test -e $PREFIX/include/logaddexp/logaddexp.h            # [unix]

about:
  home: https://github.com/horta/logaddexp
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: C library that implements the logarithm of the sum of exponentiations
  dev_url: https://github.com/horta/logaddexp

extra:
  recipe-maintainers:
    - horta
