{% set name = "logaddexp" %}
{% set version = "2.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/horta/logaddexp/archive/{{ version }}.tar.gz
  sha256: 306531607eccc153e082a9b76961db3392bf4dc6ca23c0d4f3a6c9caa06a5f13

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make  # [unix]
test:
  commands:
    - test -e $PREFIX/include/logaddexp/logaddexp.h            # [unix]

about:
  home: https://github.com/horta/logaddexp
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: C library that implements the logarithm of the sum of exponentiations
  dev_url: https://github.com/horta/logaddexp

extra:
  recipe-maintainers:
    - horta
