{% set name = "logaddexp" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/horta/logaddexp/archive/{{ version }}.tar.gz
  sha256: d100b3d58521bd15ae6371e238657b6a80ebb0381fd607cd211bbdaf34395281

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make  # [unix]
test:
  commands:
    - test -e $PREFIX/include/logaddexp/logaddexp.h            # [unix]

about:
  home: https://github.com/horta/logaddexp
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: C library that implements the logarithm of the sum of exponentiations
  dev_url: https://github.com/horta/logaddexp

extra:
  recipe-maintainers:
    - horta
