{% set name = "logaddexp" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/horta/logaddexp/archive/{{ version }}.tar.gz
  sha256: da846e58655268c28b93a77adc89f78e6595b71a81b0ca519a2d3ee2d6b267c5

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - ninja  # [win]
    - make  # [unix]
test:
  commands:
    - test -e $PREFIX/include/logaddexp.h            # [unix]
    - if NOT exist %LIBRARY_INC%/logaddexp.h exit 1  # [win]

about:
  home: https://github.com/logaddexp/logaddexp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'C library that implements the logarithm of the sum of exponentiations'
  dev_url: https://github.com/horta/logaddexp

extra:
  recipe-maintainers:
    - horta
