{% set name = "logaddexp" %}
{% set version = "2.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/horta/logaddexp/archive/{{ version }}.tar.gz
  sha256: ff3308dfdda860c9d4ea7a4a11200bd3afc63ad9218d57887c04de3e3fa11e19

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make  # [unix]
test:
  commands:
    - test -e $PREFIX/include/logaddexp/logaddexp.h            # [unix]

about:
  home: https://github.com/horta/logaddexp
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: C library that implements the logarithm of the sum of exponentiations
  dev_url: https://github.com/horta/logaddexp

extra:
  recipe-maintainers:
    - horta
