{% set name = "logaddexp" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/horta/logaddexp/archive/{{ version }}.tar.gz
  sha256: 5a5158af27ec84ea7cb946e58f3a12dfaa270ea5c392df470a6b3000ff28a54f

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - ninja  # [win]
    - make  # [unix]
test:
  commands:
    - test -e $PREFIX/include/logaddexp/logaddexp.h            # [unix]
    - if NOT exist %LIBRARY_INC%/logaddexp/logaddexp.h exit 1  # [win]

about:
  home: https://github.com/horta/logaddexp
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'C library that implements the logarithm of the sum of exponentiations'
  dev_url: https://github.com/horta/logaddexp

extra:
  recipe-maintainers:
    - horta
